Update .stderr files
With compiler 1.60.0:

  $ rustc --version
  rustc 1.60.0 (7737e0b5c 2022-04-04)

The contents of teh `.stderr` files is slightly different so the `.stderr`
files needed updating using `TRYBUILD=overwrite cargo test`.

Without this change I was getting errors like the following, with the
change the tests pass.
```
  test tests/ui/has-arguments.rs ... mismatch

  EXPECTED:
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  error: this attribute takes no arguments

    = help: use `#[contracts]`

   --> $DIR/has-arguments.rs:3:1
    |
  3 | #[contracts(a, b)]
    | ^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `contracts` (in Nightly builds, run with -Z macro-backtrace for more info)
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  ACTUAL OUTPUT:
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  error: this attribute takes no arguments

           = help: use `#[contracts]`

   --> tests/ui/has-arguments.rs:3:1
    |
  3 | #[contracts(a, b)]
    | ^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `contracts` (in Nightly builds, run with -Z macro-backtrace for more info)
  ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  note: If the actual output is the correct output you can bless it by rerunning
        your test with the environment variable TRYBUILD=overwrite

  test tests/ui/has-expr-argument.rs ... mismatch
```